enable sentinel bind usage with multi ip
voxpupuli/puppet-redis pull request #365
Opened 2020-09-16 15:14 UTC by ragingdave

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2020-09-17 12:19 UTC, ekohl reviewed
The type also allows undef and this ends up with an empty `bind` statement and breaks the tests. Please have a look at that.

2020-09-18 07:44 UTC, igalic requested changes

2020-09-18 07:44 UTC, igalic commented on manifests/sentinel.pp
> +  $sentinel_bind_arr = [$sentinel_bind].flatten
see delete_undef_values for @ekohl's comment, or it's documentation for how to do that with filter

2020-09-18 20:04 UTC, bastelfreak commented
@ragingdave thanks for the PR! Can you add a unit test for this change?

2020-09-18 20:29 UTC, bastelfreak approved these changes

2020-09-19 06:43 UTC, igalic commented on manifests/sentinel.pp
> +  $sentinel_bind_arr = delete_undef_values([$sentinel_bind]).flatten
it might make more sense to first `flatten()` and then `delete_undef_values()`

2020-09-22 21:05 UTC, merged