Add support for managing Redis APT repo
voxpupuli/puppet-redis pull request #456
Opened 2022-12-01 02:13 UTC by zaben903

#### Pull Request (PR) description
Adds support for managing the official Redis [repo](https://redis.io/docs/getting-started/installation/install-redis-on-linux/) on Debian based systems to allow installation of additional Redis versions.

#### This Pull Request (PR) fixes the following issues
n/a

2022-12-01 10:41 UTC, ekohl requested changes
IMHO it shouldn't use the Redis apt repo by default. By default it should still use the OS repos.

2022-12-01 10:41 UTC, ekohl commented on REFERENCE.md
> +Default value: `https://packages.redis.io/deb/`
This doesn't look like the real default. Normally we generate the reference using `rake strings:generate:reference`

2022-12-02 07:15 UTC, bastelfreak commented on manifests/init.pp
> +  Boolean $redis_apt_repo                                        = false,
please add the data here and not in params.pp. that enables puppet-strings to pick it up and put it into the reference.md

2022-12-02 10:30 UTC, ekohl commented on manifests/params.pp
> +      $apt_release               = $facts.dig('os', 'distro', 'codename')
This is the same value as the default in `apt::source` so I'd keep it `undef` by default rather than trying to duplicate it.

2022-12-02 10:30 UTC, ekohl commented on spec/spec_helper_acceptance.rb
> +    host.install_package('lsb-release')
Only on Facter 3. Facter 4 can extract it from `/etc/os-release`.

2022-12-05 07:42 UTC, bastelfreak approved these changes

2022-12-05 10:13 UTC, merged