add replicaof parameter(v2)
voxpupuli/puppet-redis pull request #465
Opened 2023-02-02 13:52 UTC by jonasbartho

This PR is based on https://github.com/voxpupuli/puppet-redis/pull/449 (Fixes https://github.com/voxpupuli/puppet-redis/issues/401), but without changes to REFERENCE.md.

All credit goes to @kolaCZek

2023-02-02 14:13 UTC, MindTooth commented
Thanks for doing this. 👍🏻

2023-02-02 20:33 UTC, kenyon requested changes

2023-02-02 20:33 UTC, kenyon commented on manifests/init.pp
> +  Optional[String[1]] $replicaof                                   = undef,
Hate having aligned parameter lists, but might as well keep them aligned.

```suggestion
  Optional[String[1]] $replicaof                                 = undef,
```

2023-02-02 21:40 UTC, kenyon approved these changes

2023-02-08 17:51 UTC, jonasbartho commented
Hi again, do I need to confirm something to have this PR merged..or...?

2023-02-08 18:19 UTC, merged